In [ ]:
import numpy as np
import random
numbers = list(range(0,9))
random.shuffle(numbers)
map = np.array(numbers).reshape(3,3)
print(map)


def locate():
  location = np.where(map == 0)
  location_coord = (location[0][0], location[1][0])
  return location_coord


def around():
  location = locate()
  #above
  if location[0] != 0:
    above = map[location[0] - 1, location[1]]
  else:
    above = 9
  #below
  if location[0] != 2:
    below = map[location[0] + 1, location[1]]
  else:
    below = 9
  #left
  if location[1] != 0:
    left = map[location[0], location[1] - 1]
  else:
    left = 9
  #right
  if location[1] != 2:
    right = map[location[0], location[1] + 1]
  else:
    right = 9

  return above, below, left, right



def move(direction):
  position = locate()
  above = around()[0]
  below = around()[1]
  left = around()[2]
  right = around()[3]

  if direction == "u":
    if above != 9:
      above_pos = (position[0] - 1, position[1])
      map[above_pos[0],above_pos[1]] = 0
      map[position[0],position[1]] = above
    else:
      print("Invalid move")

  elif direction == "d":
    if below != 9:
      below_pos = (position[0] + 1, position[1])
      map[below_pos[0],below_pos[1]] = 0
      map[position[0],position[1]] = below
    else:
      print("Invalid move")

  elif direction == "l":
    if left != 9:
      left_pos = (position[0], position[1] - 1)
      map[left_pos[0],left_pos[1]] = 0
      map[position[0],position[1]] = left
    else:
      print("Invalid move")

  elif direction == "r":
    if right != 9:
      right_pos = (position[0], position[1] + 1)
      map[right_pos[0],right_pos[1]] = 0
      map[position[0],position[1]] = right
    else:
      print("Invalid move")
  print("\n")
  print(map)



move("u")
move("d")
move("l")
move("r")






[[8 7 4]
 [5 3 1]
 [0 6 2]]


[[8 7 4]
 [0 3 1]
 [5 6 2]]


[[8 7 4]
 [5 3 1]
 [0 6 2]]
Invalid move


[[8 7 4]
 [5 3 1]
 [0 6 2]]


[[8 7 4]
 [5 3 1]
 [6 0 2]]
